networks:
  magics:

services:
  markdownify-crawler:
    build:
      context: .
      dockerfile: Dockerfile
    image: markdownify-crawler:latest
    container_name: markdownify-crawler
    hostname: markdownify-crawler
    restart: always
    environment:
      - MARKDOWNIFY_CACHE_DIR=/tmp/markdownify/cache
      - MARKDOWNIFY_IGNORE_PATHS=^/feed/,^/wp-json/
      - MARKDOWNIFY_IGNORE_DOMAINS=github.com,youtube.com,play.google.com
      - MARKDOWNIFY_FILTER_IGNORED_DOMAINS_IN_LINKS=true
    expose:
      - 8000
    volumes:
      # Persist HTML cache locally between runs
      - ./.cache:/tmp/markdownify/cache
    networks:
      - magics
  webapp:
    build:
      context: .
      dockerfile: webapp/Dockerfile
    image: markdownify-webapp:latest
    container_name: markdownify-webapp
    hostname: markdownify-webapp
    restart: always
    environment:
      # - SITE_BASE_URL=
      - SQLITE_PATH=/db/app.db
      - MARKDOWNIFY_CACHE_DIR=/tmp/markdownify/cache
      - MARKDOWNIFY_IGNORE_PATHS=^/feed/,^/wp-json/
      - MARKDOWNIFY_IGNORE_DOMAINS=github.com,youtube.com,play.google.com,apps.apple.com
      - MARKDOWNIFY_FILTER_IGNORED_DOMAINS_IN_LINKS=true
      - SITE_NAME=Markdownify
    volumes:
      - ./.cache:/tmp/markdownify/cache
      - ./data/webapp:/db
    ports:
      - "8080:8080"
    networks:
      - magics
