"""initial schema

Revision ID: 4c6f9c5ed377
Revises: 
Create Date: 2026-09-02 10:48:54.718185
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4c6f9c5ed377"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oauth_states',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('sid', sa.String(length=64), nullable=True),
    sa.Column('state', sa.String(length=255), nullable=False),
    sa.Column('next_path', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_oauth_states_expires_at', 'oauth_states', ['expires_at'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('provider_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.String(length=1024), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('provider', 'provider_id', name='uq_users_provider_id')
    )
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_index('ix_users_provider', 'users', ['provider', 'provider_id'], unique=False)
    op.create_table('api_keys',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('key_prefix', sa.String(length=24), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_api_keys_key_hash', 'api_keys', ['key_hash'], unique=True)
    op.create_index('ix_api_keys_user_id', 'api_keys', ['user_id'], unique=False)
    op.create_table('auth_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_activity', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_index('ix_auth_sessions_expires_at', 'auth_sessions', ['expires_at'], unique=False)
    op.create_table('crawls',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('canonical_url', sa.Text(), nullable=False),
    sa.Column('key', sa.String(length=32), nullable=True),
    sa.Column('visibility', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('payload_json', sa.JSON(), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('anonymous_user_id', sa.String(length=41), nullable=True),
    sa.Column('crawl_params', sa.JSON(), nullable=True),
    sa.Column('aeo_score', sa.Float(), nullable=True),
    sa.Column('geo_score', sa.Float(), nullable=True),
    sa.Column('aeo_rating', sa.String(length=32), nullable=True),
    sa.Column('geo_rating', sa.String(length=32), nullable=True),
    sa.Column('ai_analysis_json', sa.JSON(), nullable=True),
    sa.Column('aax_status', sa.String(length=10), server_default='pending', nullable=False),
    sa.Column('aax_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scoring_version', sa.String(length=16), nullable=False),
    sa.Column('has_manual_input', sa.Boolean(), nullable=False),
    sa.Column('listed', sa.Boolean(), nullable=False),
    sa.Column('is_latest', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key', name='uq_crawls_key')
    )
    op.create_index('ix_crawls_aax_status', 'crawls', ['aax_status', 'updated_at'], unique=False)
    op.create_index('ix_crawls_domain', 'crawls', ['domain'], unique=False)
    op.create_index('ix_crawls_domain_is_latest', 'crawls', ['domain', 'is_latest'], unique=False)
    op.create_index('ix_crawls_updated_at', 'crawls', ['updated_at'], unique=False)
    op.create_index('ix_crawls_user_id', 'crawls', ['user_id'], unique=False)
    op.create_index('ix_crawls_visibility_user_id_listed', 'crawls', ['visibility', 'user_id', 'listed'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('website', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('contact_info', sa.Text(), nullable=False),
    sa.Column('defaults_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_products_user_name')
    )
    op.create_index('ix_products_user_id', 'products', ['user_id'], unique=False)
    op.create_table('prospects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('crawl_id', sa.String(length=36), nullable=True),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('socials_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['crawl_id'], ['crawls.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'domain', name='uq_prospects_user_domain')
    )
    op.create_index('ix_prospects_domain', 'prospects', ['domain'], unique=False)
    op.create_index('ix_prospects_user_id', 'prospects', ['user_id'], unique=False)
    op.create_table('score_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('crawl_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('aeo_score', sa.Float(), nullable=True),
    sa.Column('geo_score', sa.Float(), nullable=True),
    sa.Column('aeo_rating', sa.String(length=32), nullable=True),
    sa.Column('geo_rating', sa.String(length=32), nullable=True),
    sa.Column('score_json', sa.JSON(), nullable=False),
    sa.Column('ai_analysis_json', sa.JSON(), nullable=True),
    sa.Column('scoring_version', sa.String(length=16), nullable=False),
    sa.Column('has_manual_input', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['crawl_id'], ['crawls.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('crawl_id')
    )
    op.create_index('ix_score_snapshots_created_at', 'score_snapshots', ['created_at'], unique=False)
    op.create_index('ix_score_snapshots_domain', 'score_snapshots', ['domain'], unique=False)
    op.create_index('ix_score_snapshots_user_id', 'score_snapshots', ['user_id'], unique=False)
    op.create_table('submissions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('crawl_id', sa.String(length=36), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('url_at_submit', sa.Text(), nullable=False),
    sa.Column('visibility', sa.String(length=10), nullable=False),
    sa.Column('force_refresh', sa.Boolean(), nullable=False),
    sa.Column('status_at_submit', sa.String(length=10), nullable=False),
    sa.Column('client_ip', sa.String(length=64), nullable=True),
    sa.Column('client_ip_hash', sa.String(length=64), nullable=True),
    sa.Column('forwarded_for', sa.Text(), nullable=True),
    sa.Column('x_real_ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('accept_language', sa.String(length=255), nullable=True),
    sa.Column('referer', sa.Text(), nullable=True),
    sa.Column('origin', sa.Text(), nullable=True),
    sa.Column('host', sa.String(length=255), nullable=True),
    sa.Column('session_id', sa.String(length=64), nullable=True),
    sa.Column('headers_json', sa.Text(), nullable=True),
    sa.Column('cookies_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['crawl_id'], ['crawls.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_submissions_client_ip', 'submissions', ['client_ip'], unique=False)
    op.create_index('ix_submissions_created_at', 'submissions', ['created_at'], unique=False)
    op.create_index('ix_submissions_domain', 'submissions', ['domain'], unique=False)
    op.create_index('ix_submissions_session_id', 'submissions', ['session_id'], unique=False)
    op.create_table('prospect_contacts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('prospect_id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('social_url', sa.Text(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('role_title', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['prospect_id'], ['prospects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prospect_id', 'email', name='uq_prospect_contacts_email')
    )
    op.create_index('ix_prospect_contacts_prospect_id', 'prospect_contacts', ['prospect_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_prospect_contacts_prospect_id', table_name='prospect_contacts')
    op.drop_table('prospect_contacts')
    op.drop_index('ix_submissions_session_id', table_name='submissions')
    op.drop_index('ix_submissions_domain', table_name='submissions')
    op.drop_index('ix_submissions_created_at', table_name='submissions')
    op.drop_index('ix_submissions_client_ip', table_name='submissions')
    op.drop_table('submissions')
    op.drop_index('ix_score_snapshots_user_id', table_name='score_snapshots')
    op.drop_index('ix_score_snapshots_domain', table_name='score_snapshots')
    op.drop_index('ix_score_snapshots_created_at', table_name='score_snapshots')
    op.drop_table('score_snapshots')
    op.drop_index('ix_prospects_user_id', table_name='prospects')
    op.drop_index('ix_prospects_domain', table_name='prospects')
    op.drop_table('prospects')
    op.drop_index('ix_products_user_id', table_name='products')
    op.drop_table('products')
    op.drop_index('ix_crawls_visibility_user_id_listed', table_name='crawls')
    op.drop_index('ix_crawls_user_id', table_name='crawls')
    op.drop_index('ix_crawls_updated_at', table_name='crawls')
    op.drop_index('ix_crawls_domain_is_latest', table_name='crawls')
    op.drop_index('ix_crawls_domain', table_name='crawls')
    op.drop_index('ix_crawls_aax_status', table_name='crawls')
    op.drop_table('crawls')
    op.drop_index('ix_auth_sessions_expires_at', table_name='auth_sessions')
    op.drop_table('auth_sessions')
    op.drop_index('ix_api_keys_user_id', table_name='api_keys')
    op.drop_index('ix_api_keys_key_hash', table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index('ix_users_provider', table_name='users')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_oauth_states_expires_at', table_name='oauth_states')
    op.drop_table('oauth_states')
    # ### end Alembic commands ###
