"""initial_schema

Revision ID: aa3be343c70f
Revises:
Create Date: 2025-09-14 10:44:04.180785
"""

from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "aa3be343c70f"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "oauth_states",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("sid", sa.String(length=64), nullable=True),
        sa.Column("state", sa.String(length=255), nullable=False),
        sa.Column("next_path", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_oauth_states_expires_at", "oauth_states", ["expires_at"], unique=False
    )
    op.create_table(
        "users",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("provider_id", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("avatar_url", sa.String(length=1024), nullable=True),
        sa.Column("is_admin", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("provider", "provider_id", name="uq_users_provider_id"),
    )
    op.create_index("ix_users_email", "users", ["email"], unique=False)
    op.create_index(
        "ix_users_provider", "users", ["provider", "provider_id"], unique=False
    )
    op.create_table(
        "auth_sessions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("session_id", sa.String(length=128), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_activity", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("session_id"),
    )
    op.create_index(
        "ix_auth_sessions_expires_at", "auth_sessions", ["expires_at"], unique=False
    )
    op.create_index(
        "ix_auth_sessions_session_id", "auth_sessions", ["session_id"], unique=False
    )
    op.create_table(
        "crawls",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("domain", sa.String(length=255), nullable=False),
        sa.Column("path", sa.Text(), nullable=False),
        sa.Column("query", sa.Text(), nullable=False),
        sa.Column("canonical_url", sa.Text(), nullable=False),
        sa.Column("key", sa.String(length=32), nullable=True),
        sa.Column("visibility", sa.String(length=10), nullable=False),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("payload_json", sa.Text(), nullable=True),
        sa.Column("user_id", sa.String(length=36), nullable=True),
        sa.Column("scope", sa.String(length=10), nullable=False),
        sa.Column("limits_json", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key", name="uq_crawls_key"),
        sa.UniqueConstraint(
            "visibility", "domain", "path", "query", name="uq_crawls_vis_dom_path_query"
        ),
    )
    op.create_index("ix_crawls_domain", "crawls", ["domain"], unique=False)
    op.create_index("ix_crawls_scope", "crawls", ["scope"], unique=False)
    op.create_index("ix_crawls_updated_at", "crawls", ["updated_at"], unique=False)
    op.create_index("ix_crawls_user_id", "crawls", ["user_id"], unique=False)
    op.create_table(
        "crawl_emails",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("crawl_id", sa.String(length=36), nullable=False),
        sa.Column("page_url", sa.Text(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("found_as", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["crawl_id"], ["crawls.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "crawl_id", "page_url", "email", name="uq_crawl_emails_unique"
        ),
    )
    op.create_index(
        "ix_crawl_emails_crawl_id", "crawl_emails", ["crawl_id"], unique=False
    )
    op.create_index("ix_crawl_emails_email", "crawl_emails", ["email"], unique=False)
    op.create_table(
        "crawl_links",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("crawl_id", sa.String(length=36), nullable=False),
        sa.Column("page_url", sa.Text(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("absolute_url", sa.Text(), nullable=False),
        sa.Column("type", sa.String(length=10), nullable=False),
        sa.Column("domain", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["crawl_id"], ["crawls.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "crawl_id", "page_url", "absolute_url", "type", name="uq_crawl_links_unique"
        ),
    )
    op.create_index("ix_crawl_links_crawl_id", "crawl_links", ["crawl_id"], unique=False)
    op.create_index("ix_crawl_links_domain", "crawl_links", ["domain"], unique=False)
    op.create_index("ix_crawl_links_type", "crawl_links", ["type"], unique=False)
    op.create_table(
        "submissions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("crawl_id", sa.String(length=36), nullable=False),
        sa.Column("domain", sa.String(length=255), nullable=False),
        sa.Column("url_at_submit", sa.Text(), nullable=False),
        sa.Column("visibility", sa.String(length=10), nullable=False),
        sa.Column("force_refresh", sa.Boolean(), nullable=False),
        sa.Column("status_at_submit", sa.String(length=10), nullable=False),
        sa.Column("client_ip", sa.String(length=64), nullable=True),
        sa.Column("client_ip_hash", sa.String(length=64), nullable=True),
        sa.Column("forwarded_for", sa.Text(), nullable=True),
        sa.Column("x_real_ip", sa.String(length=64), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column("accept_language", sa.String(length=255), nullable=True),
        sa.Column("referer", sa.Text(), nullable=True),
        sa.Column("origin", sa.Text(), nullable=True),
        sa.Column("host", sa.String(length=255), nullable=True),
        sa.Column("session_id", sa.String(length=64), nullable=True),
        sa.Column("headers_json", sa.Text(), nullable=True),
        sa.Column("cookies_json", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["crawl_id"], ["crawls.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_submissions_client_ip", "submissions", ["client_ip"], unique=False
    )
    op.create_index(
        "ix_submissions_created_at", "submissions", ["created_at"], unique=False
    )
    op.create_index("ix_submissions_domain", "submissions", ["domain"], unique=False)
    op.create_index(
        "ix_submissions_session_id", "submissions", ["session_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_submissions_session_id", table_name="submissions")
    op.drop_index("ix_submissions_domain", table_name="submissions")
    op.drop_index("ix_submissions_created_at", table_name="submissions")
    op.drop_index("ix_submissions_client_ip", table_name="submissions")
    op.drop_table("submissions")
    op.drop_index("ix_crawl_links_type", table_name="crawl_links")
    op.drop_index("ix_crawl_links_domain", table_name="crawl_links")
    op.drop_index("ix_crawl_links_crawl_id", table_name="crawl_links")
    op.drop_table("crawl_links")
    op.drop_index("ix_crawl_emails_email", table_name="crawl_emails")
    op.drop_index("ix_crawl_emails_crawl_id", table_name="crawl_emails")
    op.drop_table("crawl_emails")
    op.drop_index("ix_crawls_user_id", table_name="crawls")
    op.drop_index("ix_crawls_updated_at", table_name="crawls")
    op.drop_index("ix_crawls_scope", table_name="crawls")
    op.drop_index("ix_crawls_domain", table_name="crawls")
    op.drop_table("crawls")
    op.drop_index("ix_auth_sessions_session_id", table_name="auth_sessions")
    op.drop_index("ix_auth_sessions_expires_at", table_name="auth_sessions")
    op.drop_table("auth_sessions")
    op.drop_index("ix_users_provider", table_name="users")
    op.drop_index("ix_users_email", table_name="users")
    op.drop_table("users")
    op.drop_index("ix_oauth_states_expires_at", table_name="oauth_states")
    op.drop_table("oauth_states")
    # ### end Alembic commands ###
