"""Add listed and share_key columns to Crawl

Revision ID: ef508401381b
Revises: 6867113818f4
Create Date: 2025-10-05 12:06:31.925529
"""

from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ef508401381b"
down_revision: Union[str, None] = "6867113818f4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "crawls",
        sa.Column("listed", sa.Boolean(), nullable=False, server_default=sa.text("true")),
    )
    op.add_column("crawls", sa.Column("share_key", sa.String(length=32), nullable=True))
    op.create_unique_constraint("uq_crawls_share_key", "crawls", ["share_key"])
    op.create_index(
        "ix_crawls_visibility_user_id_listed",
        "crawls",
        ["visibility", "user_id", "listed"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_crawls_visibility_user_id_listed", table_name="crawls")
    op.drop_constraint("uq_crawls_share_key", "crawls", type_="unique")
    op.drop_column("crawls", "share_key")
    op.drop_column("crawls", "listed")
    # ### end Alembic commands ###
