"""phase 1b models

Revision ID: f465b7dd1685
Revises: aa3be343c70f
Create Date: 2025-09-16 06:51:27.794862
"""

from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f465b7dd1685"
down_revision: Union[str, None] = "aa3be343c70f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "products",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("website", sa.Text(), nullable=True),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("icp", sa.Text(), nullable=True),
        sa.Column("pricing", sa.Text(), nullable=True),
        sa.Column("tone", sa.Text(), nullable=True),
        sa.Column("contact_info", sa.Text(), nullable=True),
        sa.Column("defaults_json", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "name", name="uq_products_user_name"),
    )
    op.create_index("ix_products_user_id", "products", ["user_id"], unique=False)
    op.create_table(
        "prospects",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("crawl_id", sa.String(length=36), nullable=True),
        sa.Column("domain", sa.String(length=255), nullable=False),
        sa.Column("url", sa.Text(), nullable=True),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("tags", sa.Text(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("socials_json", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["crawl_id"], ["crawls.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "domain", name="uq_prospects_user_domain"),
    )
    op.create_index("ix_prospects_domain", "prospects", ["domain"], unique=False)
    op.create_index("ix_prospects_user_id", "prospects", ["user_id"], unique=False)
    op.create_table(
        "prospect_contacts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("prospect_id", sa.String(length=36), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=True),
        sa.Column("social_url", sa.Text(), nullable=True),
        sa.Column("tags", sa.Text(), nullable=True),
        sa.Column("role_title", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["prospect_id"], ["prospects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("prospect_id", "email", name="uq_prospect_contacts_email"),
    )
    op.create_index(
        "ix_prospect_contacts_email", "prospect_contacts", ["email"], unique=False
    )
    op.create_index(
        "ix_prospect_contacts_prospect_id",
        "prospect_contacts",
        ["prospect_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_prospect_contacts_prospect_id", table_name="prospect_contacts")
    op.drop_index("ix_prospect_contacts_email", table_name="prospect_contacts")
    op.drop_table("prospect_contacts")
    op.drop_index("ix_prospects_user_id", table_name="prospects")
    op.drop_index("ix_prospects_domain", table_name="prospects")
    op.drop_table("prospects")
    op.drop_index("ix_products_user_id", table_name="products")
    op.drop_table("products")
    # ### end Alembic commands ###
